/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saarah Packeer
 */
public class AdminAcc extends javax.swing.JFrame {

    /**
     * Creates new form AdminAcc
     */
    
    String searchedUser;
    Admin admin = new Admin("Jack Williams","jack123","Admin");
    String[] values = null;
    List<User> enteredusers = new ArrayList<User>();
    List<Student> studentdatabase = new ArrayList<Student>();
    List<Librarian> librariandatabase = new ArrayList<Librarian>();
    String line, username, name, usertype;
    List<User> userdatabase = new ArrayList<User>();
    String enteredUsername;
    
    public AdminAcc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userradiobuttons = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        loadUsers = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        editStud = new javax.swing.JButton();
        getUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        editStud1 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        getname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        getusername = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        getpassword = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        getcourse = new javax.swing.JTextField();
        creatstudent = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        newnam = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        changeusername = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        newun = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        newpass = new javax.swing.JTextField();
        getun = new javax.swing.JButton();
        changerecord = new javax.swing.JButton();
        newcours = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        loadUsers1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        getUsername1 = new javax.swing.JTextField();
        editStud2 = new javax.swing.JButton();
        editStud3 = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        getname1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        getusername1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        getpassword1 = new javax.swing.JTextField();
        creatstudent1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        newnam1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        changeusername1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        newun1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        newpass1 = new javax.swing.JTextField();
        getun1 = new javax.swing.JButton();
        changerecord1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loadUsers.setText("View all current students");
        loadUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadUsersMouseClicked(evt);
            }
        });

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Full Name", "Username", "Password", "Course"
            }
        ));
        jScrollPane1.setViewportView(table1);

        editStud.setText("Search");
        editStud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editStudMouseClicked(evt);
            }
        });

        jLabel1.setText("Enter username/name:");

        editStud1.setText("Delete Student");
        editStud1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editStud1MouseClicked(evt);
            }
        });

        jLabel7.setText("Name:");

        jLabel8.setText("Username:");

        jLabel9.setText("Password:");

        jLabel11.setText("Course:");

        creatstudent.setText("Add Student");
        creatstudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creatstudentMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(getpassword)
                    .addComponent(getusername)
                    .addComponent(getname)
                    .addComponent(getcourse)
                    .addComponent(creatstudent, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(getname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(getusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(getpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(getcourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(creatstudent)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add Student", jPanel3);

        jLabel14.setText("Name:");

        jLabel15.setText("Username:");

        jLabel16.setText("Username:");

        jLabel17.setText("Password:");

        getun.setText("Get accound to edit");
        getun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getunMouseClicked(evt);
            }
        });

        changerecord.setText("Alter account");
        changerecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changerecordMouseClicked(evt);
            }
        });

        jLabel18.setText("Course:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newun, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newnam, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newpass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newcours, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(changeusername))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changerecord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(getun, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(changeusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(getun)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(newnam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(newun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(newpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newcours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addComponent(changerecord, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Edit Student", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(loadUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(editStud, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editStud1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(getUsername)))
                    .addComponent(jTabbedPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loadUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(getUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editStud)
                    .addComponent(editStud1))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Student Accounts", jPanel1);

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Full Name", "Username", "Password"
            }
        ));
        jScrollPane2.setViewportView(table2);

        loadUsers1.setText("View all current librarians");
        loadUsers1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadUsers1MouseClicked(evt);
            }
        });

        jLabel2.setText("Enter username/name:");

        editStud2.setText("Search");
        editStud2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editStud2MouseClicked(evt);
            }
        });

        editStud3.setText("Delete Librarian");
        editStud3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                editStud3MouseDragged(evt);
            }
        });
        editStud3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editStud3MouseClicked(evt);
            }
        });

        jLabel19.setText("Name:");

        jLabel20.setText("Username:");

        jLabel21.setText("Password:");

        creatstudent1.setText("Add Librarian");
        creatstudent1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creatstudent1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(getpassword1)
                    .addComponent(getusername1)
                    .addComponent(getname1)
                    .addComponent(creatstudent1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(getname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(getusername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(getpassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(creatstudent1)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Add Librarian", jPanel5);

        jLabel23.setText("Name:");

        jLabel24.setText("Username:");

        jLabel25.setText("Username:");

        jLabel26.setText("Password:");

        getun1.setText("Get accound to edit");
        getun1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getun1MouseClicked(evt);
            }
        });

        changerecord1.setText("Alter account");
        changerecord1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changerecord1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(getun1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                            .addComponent(changeusername1)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changerecord1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newnam1)
                            .addComponent(newun1)
                            .addComponent(newpass1))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(changeusername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(getun1)
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(newnam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(newun1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(newpass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(changerecord1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Edit Librarian", jPanel6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(editStud2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editStud3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(getUsername1)))
                    .addComponent(loadUsers1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(loadUsers1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(getUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editStud2)
                    .addComponent(editStud3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane3)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Librarian Accounts", jPanel2);

        jButton1.setText("Logout");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadUsers1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadUsers1MouseClicked
        // TODO add your handling code here:

        DefaultTableModel dm = (DefaultTableModel)table2.getModel();
        while(dm.getRowCount()>0) {
            for(int i=0; i<dm.getRowCount(); i++) {
            dm.removeRow(i);
        }
        }
        
        admin.loadLibrarians(librariandatabase);
        for(Librarian l : librariandatabase) {
            String[] data = {l.getFullname(), l.getUsername(), l.getPassword()};
            dm.addRow(data);

        }

    }//GEN-LAST:event_loadUsers1MouseClicked

    private void loadUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadUsersMouseClicked
        
        DefaultTableModel dm = (DefaultTableModel)table1.getModel();
        while(dm.getRowCount()>0) {
            for(int i=0; i<dm.getRowCount(); i++) {
            dm.removeRow(i);
        }
        }
        
        String course;
        admin.loadStudents(studentdatabase);

        for(Student s : studentdatabase) {
            /*
            if(u.getUserType().contains("student")){
                course = u.getCourse();
            }*/
            String[] data = {s.getFullname(), s.getUsername(), s.getPassword(), s.getCourse()};
            dm.addRow(data);

        }

    }//GEN-LAST:event_loadUsersMouseClicked

    private void editStudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editStudMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel dm = (DefaultTableModel)table1.getModel();
        while(dm.getRowCount()>0) {
            for(int i=0; i<dm.getRowCount(); i++) {
            dm.removeRow(i);
        }
        }
        
        
        List<Student> studentsearch = new ArrayList<Student>(); 
        admin.loadStudents(studentdatabase);  
        Student found = null;
        try {
            searchedUser = getUsername.getText();
        
            for (Student s : studentdatabase) {
                if (searchedUser.equals(s.getUsername()) || s.getFullname().contains(searchedUser)) {
                found = s;
                studentsearch.add(s);
            } 
        }

        
        for(int i=0; i<studentsearch.size(); i++) {
            String[] data = {studentsearch.get(i).getFullname(),studentsearch.get(i).getUsername(),studentsearch.get(i).getPassword(),studentsearch.get(i).getCourse()};
            dm.addRow(data);
        }      
        } catch (Exception e){
            JOptionPane.showMessageDialog(new JFrame(), "Error: "+e);
        }

    }//GEN-LAST:event_editStudMouseClicked

    private void editStud1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editStud1MouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel dm = (DefaultTableModel)table1.getModel();
        while(dm.getRowCount()>0) {
            for(int i=0; i<dm.getRowCount(); i++) {
            dm.removeRow(i);
        }
        }
        
        admin.loadStudents(studentdatabase); 
        try {
            studentdatabase = admin.deleteStudent(getUsername.getText(), studentdatabase);
            admin.writeStudentsFile(studentdatabase);
            admin.loadStudents(studentdatabase); 
        } catch (IOException ex) {
            Logger.getLogger(LibrarianAcc.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(new JFrame(), "Error: "+ex);
        }
        for(Student s: studentdatabase) {
        String[] data = {s.getFullname(),s.getUsername(), s.getPassword(), s.getCourse()};
        dm.addRow(data);
        }
        
    }//GEN-LAST:event_editStud1MouseClicked

    private void editStud2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editStud2MouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel dm = (DefaultTableModel)table2.getModel();
        while(dm.getRowCount()>0) {
            for(int i=0; i<dm.getRowCount(); i++) {
            dm.removeRow(i);
        }
        }
        
        
        List<Librarian> librariansearch = new ArrayList<Librarian>(); 
        admin.loadLibrarians(librariandatabase);  
        Librarian found = null;
        try {
            searchedUser = getUsername1.getText();
        
            for (Librarian l : librariandatabase) {
                if (searchedUser.equals(l.getUsername()) || l.getFullname().contains(searchedUser)) {
                found = l;
                librariansearch.add(l);
            } 
        }

        
        for(int i=0; i<librariansearch.size(); i++) {
            String[] data = {librariansearch.get(i).getFullname(),librariansearch.get(i).getUsername(),librariansearch.get(i).getPassword()};
            dm.addRow(data);
        }      
        } catch (Exception e){
            JOptionPane.showMessageDialog(new JFrame(), "Error: "+e);
        }
        
        
    }//GEN-LAST:event_editStud2MouseClicked

    private void editStud3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editStud3MouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel dm = (DefaultTableModel)table2.getModel();
        while(dm.getRowCount()>0) {
            for(int i=0; i<dm.getRowCount(); i++) {
            dm.removeRow(i);
        }
        }
        
        admin.loadLibrarians(librariandatabase); 
        try {
            librariandatabase = admin.deleteLibrarian(getUsername1.getText(), librariandatabase);
            admin.writeLibrariansFile(librariandatabase);
            admin.loadLibrarians(librariandatabase); 
        } catch (IOException ex) {
            Logger.getLogger(LibrarianAcc.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(new JFrame(), "Error: "+ex);
        }
        for(Librarian l: librariandatabase) {
        String[] data = {l.getFullname(),l.getUsername(), l.getPassword()};
        dm.addRow(data);
        }
        
    }//GEN-LAST:event_editStud3MouseClicked

    private void creatstudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creatstudentMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel dm = (DefaultTableModel)table1.getModel();
        while(dm.getRowCount()>0) {
            for(int i=0; i<dm.getRowCount(); i++) {
            dm.removeRow(i);
        }
        }
        
        
        try {
        Student s = new Student(getname.getText(), getusername.getText(), getpassword.getText(), "Student", getcourse.getText());
        admin.addStudent(s, studentdatabase);        
        studentdatabase.clear();
        admin.loadStudents(studentdatabase);    
        JOptionPane.showMessageDialog(new JFrame(), "You have successfully created a new Student account!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), "Error:"+e);
        }
        
        
        for(Student s: studentdatabase) {
        String[] data = {s.getFullname(),s.getUsername(),s.getPassword(),s.getCourse()};
        dm.addRow(data);
        }
        
    }//GEN-LAST:event_creatstudentMouseClicked

    private void getunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getunMouseClicked
        // TODO add your handling code here:
        
        enteredUsername = changeusername.getText();
        
    }//GEN-LAST:event_getunMouseClicked

    private void changerecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changerecordMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel)table1.getModel();
        while(dm.getRowCount()>0) {
            for(int i=0; i<dm.getRowCount(); i++) {
            dm.removeRow(i);
        }
        }
           
        
        
        admin.loadStudents(studentdatabase); 
        try {       
            String newname = newnam.getText();
            String newusername = newun.getText();
            String newpassword = newpass.getText();
            String newcourse = newcours.getText();
            studentdatabase = admin.editStudent(enteredUsername ,studentdatabase, newname, newusername, newpassword, newcourse);
            admin.writeStudentsFile(studentdatabase);
            admin.loadStudents(studentdatabase); 
        } catch (IOException ex) {
            Logger.getLogger(LibrarianAcc.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(new JFrame(), "Error: "+ex);
        }
        for(Student s: studentdatabase) {
        String[] data = {s.getFullname(),s.getUsername(),s.getPassword(),s.getCourse()};
        dm.addRow(data);
        }    
        
    }//GEN-LAST:event_changerecordMouseClicked

    private void editStud3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editStud3MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_editStud3MouseDragged

    private void creatstudent1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creatstudent1MouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel dm = (DefaultTableModel)table2.getModel();
        while(dm.getRowCount()>0) {
            for(int i=0; i<dm.getRowCount(); i++) {
            dm.removeRow(i);
        }
        }
        
        
        try {
        Librarian l = new Librarian(getname1.getText(), getusername1.getText(), getpassword1.getText(), "Librarian");
        admin.addLibrarian(l, librariandatabase);        
        librariandatabase.clear();
        admin.loadLibrarians(librariandatabase);    
        JOptionPane.showMessageDialog(new JFrame(), "You have successfully created a new Librarian account!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), "Error:"+e);
        }
        
        
        for(Librarian l: librariandatabase) {
        String[] data = {l.getFullname(),l.getUsername(),l.getPassword()};
        dm.addRow(data);
        }
        
    }//GEN-LAST:event_creatstudent1MouseClicked

    private void getun1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getun1MouseClicked
        // TODO add your handling code here:
        
        enteredUsername = changeusername1.getText();
        
    }//GEN-LAST:event_getun1MouseClicked

    private void changerecord1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changerecord1MouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel dm = (DefaultTableModel)table2.getModel();
        while(dm.getRowCount()>0) {
            for(int i=0; i<dm.getRowCount(); i++) {
            dm.removeRow(i);
        }
        }
           
        
        
        admin.loadLibrarians(librariandatabase); 
        try {       
            String newname = newnam1.getText();
            String newusername = newun1.getText();
            String newpassword = newpass1.getText();;
            librariandatabase = admin.editLibrarian(enteredUsername ,librariandatabase, newname, newusername, newpassword);
            admin.writeLibrariansFile(librariandatabase);
            admin.loadLibrarians(librariandatabase); 
        } catch (IOException ex) {
            Logger.getLogger(LibrarianAcc.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(new JFrame(), "Error: "+ex);
        }
        for(Librarian l: librariandatabase) {
        String[] data = {l.getFullname(),l.getUsername(),l.getPassword()};
        dm.addRow(data);
        } 
        
        
    }//GEN-LAST:event_changerecord1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        dispose();
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAcc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changerecord;
    private javax.swing.JButton changerecord1;
    private javax.swing.JTextField changeusername;
    private javax.swing.JTextField changeusername1;
    private javax.swing.JButton creatstudent;
    private javax.swing.JButton creatstudent1;
    private javax.swing.JButton editStud;
    private javax.swing.JButton editStud1;
    private javax.swing.JButton editStud2;
    private javax.swing.JButton editStud3;
    private javax.swing.JTextField getUsername;
    private javax.swing.JTextField getUsername1;
    private javax.swing.JTextField getcourse;
    private javax.swing.JTextField getname;
    private javax.swing.JTextField getname1;
    private javax.swing.JTextField getpassword;
    private javax.swing.JTextField getpassword1;
    private javax.swing.JButton getun;
    private javax.swing.JButton getun1;
    private javax.swing.JTextField getusername;
    private javax.swing.JTextField getusername1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JButton loadUsers;
    private javax.swing.JButton loadUsers1;
    private javax.swing.JTextField newcours;
    private javax.swing.JTextField newnam;
    private javax.swing.JTextField newnam1;
    private javax.swing.JTextField newpass;
    private javax.swing.JTextField newpass1;
    private javax.swing.JTextField newun;
    private javax.swing.JTextField newun1;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.ButtonGroup userradiobuttons;
    // End of variables declaration//GEN-END:variables
}
