/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saarah Packeer
 */
public class LibrarianAcc extends javax.swing.JFrame {

    /**
     * Creates new form LibrarianAcc
     */
    
    // declare variables
    Librarian l = new Librarian("Matt Williams", "mattw123", "pass", "librarian");
    Book b;
    List<Book> bookdatabase = new ArrayList<Book>();
    List<String> reservedbookdatabase = new ArrayList<String>();
    List<Book> bookcollection;
    int ISBN;
    String[] values;
    String line;
    String grade, stud, mark;
    List<String> books = new ArrayList<String>();
    String luser;
    
    public LibrarianAcc() {
        
    }
    
    
    public LibrarianAcc(String loggedon) {
        initComponents();
        this.luser = loggedon;
        loggedonuser.setText(luser);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        isbn = new javax.swing.JTextField();
        title = new javax.swing.JTextField();
        author = new javax.swing.JTextField();
        edition = new javax.swing.JTextField();
        pubdate = new javax.swing.JTextField();
        keywords = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        addBookButton = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        isbn1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        title1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        author1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        edition1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        pubdate1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        keywords1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        location1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        status1 = new javax.swing.JTextField();
        editBookButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        findBook1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        findBookB1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        update = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        findBook = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        findBookB = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        loggedonuser = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Book ISBN:");

        jLabel2.setText("Title:");

        jLabel3.setText("Author(s):");

        jLabel4.setText("Edition:");

        jLabel5.setText("Publication Date:");

        jLabel6.setText("Keywords(use>between each):");

        jLabel7.setText("Location:");

        jLabel8.setText("Status:");

        author.setText(" ");
        author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorActionPerformed(evt);
            }
        });

        edition.setText(" ");

        pubdate.setText(" ");

        addBookButton.setText("Add Book");
        addBookButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBookButtonMouseClicked(evt);
            }
        });

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Title", "Author", "Edition", "Pub Date", "Keywords", "Location", "Status"
            }
        ));
        jScrollPane6.setViewportView(table2);

        jButton3.setText("View All Book Records");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                        .addComponent(addBookButton, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                        .addComponent(edition)
                        .addComponent(pubdate, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(author)
                        .addComponent(title)
                        .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(keywords)
                        .addComponent(location)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(pubdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keywords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addBookButton)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Create a book record", jPanel1);

        jLabel9.setText("Enter ISBN:");

        jLabel10.setText("Title:");

        jLabel11.setText("Author(s):");

        author1.setText(" ");
        author1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                author1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Edition:");

        edition1.setText(" ");

        jLabel13.setText("Publication Date:");

        pubdate1.setText(" ");

        jLabel14.setText("Keywords:");

        jLabel15.setText("Location:");

        jLabel16.setText("Status:");

        editBookButton.setText("Edit Book");
        editBookButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBookButtonMouseClicked(evt);
            }
        });

        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Title", "Author", "Edition", "Publication Date", "Keywords", "Location", "Status"
            }
        ));
        jScrollPane7.setViewportView(table3);

        jButton2.setText("Get book record to edit");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(author1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keywords1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editBookButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(isbn1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(pubdate1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edition1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                    .addComponent(location1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                    .addComponent(title1))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(isbn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(title1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(author1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edition1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pubdate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(keywords1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(location1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(status1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(editBookButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Edit a book record", jPanel2);

        jLabel18.setText("Enter Book ISBN:");

        findBookB1.setText("Search for book to delete");
        findBookB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findBookB1MouseClicked(evt);
            }
        });

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Title", "Author", "Edition", "Publication Date", "Keywords", "Location", "Status"
            }
        ));
        jScrollPane5.setViewportView(table1);

        update.setText("Delete Book");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(findBook1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(findBookB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(findBook1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findBookB1)
                    .addComponent(update))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Delete a book record", jPanel4);

        jLabel17.setText("Enter Book ISBN:");

        findBookB.setText("View Book Record");
        findBookB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findBookBMouseClicked(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Title", "Author", "Edition", "Publication Date", "Keywords", "Location", "Status"
            }
        ));
        jScrollPane4.setViewportView(table);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel17)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(findBookB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(findBook, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 79, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(findBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findBookB)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(334, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View a book record", jPanel6);

        loggedonuser.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        loggedonuser.setText("user");
        loggedonuser.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButton1.setText("Create a book reservation report");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton4.setText("Logout");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loggedonuser, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(3, 3, 3)
                        .addComponent(jButton4)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loggedonuser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorActionPerformed

    private void addBookButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBookButtonMouseClicked
        
        DefaultTableModel dm = (DefaultTableModel)table2.getModel();
        while(dm.getRowCount()>0) {
            for(int i=0; i<dm.getRowCount(); i++) {
            dm.removeRow(i);
            }
        }
        
        if(isbn.getText().equals("") || isbn.getText().equals("") || author.getText().equals("") || edition.getText().equals("") || pubdate.getText().equals("") || keywords.getText().equals("") || location.getText().equals("") || status.getText().equals("") ) {
            JOptionPane.showMessageDialog(new JFrame(), "Please enter data in all fields.");
        } else {
            try {
                b = new Book(isbn.getText(), title.getText(), author.getText(), edition.getText(), pubdate.getText(), keywords.getText(), location.getText(), status.getText());
                l.addBook(b, bookdatabase);        
                bookdatabase.clear();
                l.loadBooks(bookdatabase);    
                JOptionPane.showMessageDialog(new JFrame(), "You have successfully added a new Book record");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(new JFrame(), "Error:"+e);
            }
            for(Book b: bookdatabase) {
                String[] data = {b.getISBN(),b.getTitle(),b.getAuthor(),b.getEdition(),b.getPubdate(),b.getTerms(),b.getLocation(),b.getStatus()};
                dm.addRow(data);
            }            
        }
        
        
        
        
        
               
        
    }//GEN-LAST:event_addBookButtonMouseClicked

    private void author1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_author1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_author1ActionPerformed

    private void editBookButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBookButtonMouseClicked
        DefaultTableModel dm = (DefaultTableModel)table3.getModel();
        while(dm.getRowCount()>0) {
            for(int i=0; i<dm.getRowCount(); i++) {
            dm.removeRow(i);
        }
        }
           
        
        
        l.loadBooks(bookdatabase); 
        try {
            String enteredISBN = isbn1.getText();        
            bookdatabase = l.editBook(enteredISBN, bookdatabase, isbn1.getText(), title1.getText(), author1.getText(), edition1.getText(), pubdate1.getText(), keywords1.getText(), location1.getText(), status1.getText());
            l.writeFile(bookdatabase);
            l.loadBooks(bookdatabase); 
        } catch (IOException ex) {
            Logger.getLogger(LibrarianAcc.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(Book b: bookdatabase) {
        String[] data = {b.getISBN(),b.getTitle(),b.getAuthor(),b.getEdition(),b.getPubdate(),b.getTerms(),b.getLocation(),b.getStatus()};
        dm.addRow(data);
        }        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_editBookButtonMouseClicked

    private void findBookBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findBookBMouseClicked
        // TODO add your handling code here:
        
        if(findBook.getText().equals("")) {
                JOptionPane.showMessageDialog(new JFrame(), "No ISBN entered.");
        } else {
            if(findBook.getText().chars().allMatch(Character::isDigit)) {
                bookdatabase.clear();
                l.loadBooks(bookdatabase);  
                Book found = null;
                try {
                    String entered = findBook.getText();
                    for (Book bookk : bookdatabase) {
                        if (entered.equals(bookk.getISBN())) {
                        found = bookk;
                        } 
                    }        
                    
                    DefaultTableModel dm = (DefaultTableModel)table.getModel();
                    String[] data = {found.getISBN(),found.getTitle(),found.getAuthor(),found.getEdition(),found.getPubdate(),found.getTerms(),found.getLocation(),found.getStatus()};
                    dm.addRow(data);
                } catch (Exception e){
                    System.out.println("error: "+e);
                    JOptionPane.showMessageDialog(new JFrame(), "ERROR: The book does not exist.");
                }
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "The ISBN can only be digits.");
            }
        }      
        
        

        
    }//GEN-LAST:event_findBookBMouseClicked

    private void findBookB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findBookB1MouseClicked
        // TODO add your handling code here:
        
        if(findBook1.getText().equals("")) {
            JOptionPane.showMessageDialog(new JFrame(), "There is no ISBN entered.");
        } else {
            DefaultTableModel dm = (DefaultTableModel)table1.getModel();
            while(dm.getRowCount()>0) {
            for(int i=0; i<dm.getRowCount(); i++) {
            dm.removeRow(i);
        }
        } 
        
        
            List<Book> keywordsearch = new ArrayList<Book>(); 
            l.loadBooks(bookdatabase);  
            Book found = null;
            try {
                String enteredisbn = findBook1.getText();
        
                for (Book bookk : bookdatabase) {
                if (enteredisbn.equals(bookk.getISBN()) || enteredisbn.equals(bookk.getTitle()) || bookk.getTerms().contains(enteredisbn)) {
                    found = bookk;
                    keywordsearch.add(bookk);
            } 
        }

        for(int i=0; i<keywordsearch.size(); i++) {
            String[] data = {keywordsearch.get(i).getISBN(),keywordsearch.get(i).getTitle(),keywordsearch.get(i).getAuthor(),keywordsearch.get(i).getEdition(),keywordsearch.get(i).getPubdate(),keywordsearch.get(i).getTerms(),keywordsearch.get(i).getLocation(),keywordsearch.get(i).getStatus()};
            dm.addRow(data);
        }      
        } catch (Exception e){
            System.out.println("error: "+e);
        }
        }
        
        
    }//GEN-LAST:event_findBookB1MouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel)table1.getModel();
        while(dm.getRowCount()>0) {
            for(int i=0; i<dm.getRowCount(); i++) {
            dm.removeRow(i);
        }
        }
        
        l.loadBooks(bookdatabase); 
        try {
            bookdatabase = l.deleteStuff(findBook1.getText(), bookdatabase);
            l.writeFile(bookdatabase);
            l.loadBooks(bookdatabase); 
        } catch (IOException ex) {
            Logger.getLogger(LibrarianAcc.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(Book b: bookdatabase) {
        String[] data = {b.getISBN(),b.getTitle(),b.getAuthor(),b.getEdition(),b.getPubdate(),b.getTerms(),b.getLocation(),b.getStatus()};
        dm.addRow(data);
        }
    }//GEN-LAST:event_updateMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        reservedbookdatabase = l.loadReservedBooks(reservedbookdatabase);
        
        JOptionPane.showMessageDialog(new JFrame(), "Book report successfully generated!");
       
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        
        if(isbn1.getText().equals("")) {
            JOptionPane.showMessageDialog(new JFrame(), "Please enter a valid ISBN.");
        } else {
            if(findBook.getText().chars().allMatch(Character::isDigit)) {
                bookdatabase.clear();
                l.loadBooks(bookdatabase);  
                Book found = null;
                try {
                String entered = isbn1.getText();
                for (Book bookk : bookdatabase) {
                    if (entered.equals(bookk.getISBN())) {
                        found = bookk;
                        title1.setText(found.getTitle());
                        author1.setText(found.getAuthor());
                        edition1.setText(found.getEdition());
                        pubdate1.setText(found.getPubdate());
                        keywords1.setText(found.getTerms());
                        location1.setText(found.getLocation());
                        status1.setText(found.getStatus());
                        JOptionPane.showMessageDialog(new JFrame(), "Book found!");
                    } 
                }
                if (!entered.equals(found.getISBN()))  {
                    JOptionPane.showMessageDialog(new JFrame(), "Book not found.");
                } 
                
                DefaultTableModel dm = (DefaultTableModel)table.getModel();
                String[] data = {found.getISBN(),found.getTitle(),found.getAuthor(),found.getEdition(),found.getPubdate(),found.getTerms(),found.getLocation(),found.getStatus()};
                dm.addRow(data);
                } catch (Exception e){
                    System.out.println("error: "+e);
                }
            }
        }
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel dm = (DefaultTableModel)table2.getModel();
        while(dm.getRowCount()>0) {
            for(int i=0; i<dm.getRowCount(); i++) {
            dm.removeRow(i);
        }
        }
        
        
        bookdatabase.clear();
        l.loadBooks(bookdatabase);  
        
        try {

        
        for(Book b : bookdatabase) {
            String[] data = {b.getISBN(),b.getTitle(),b.getAuthor(),b.getEdition(),b.getPubdate(),b.getTerms(),b.getLocation(),b.getStatus()};
            dm.addRow(data);
        }      
        } catch (Exception e){
            System.out.println("error: "+e);
        }
        
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        
        dispose();
        
    }//GEN-LAST:event_jButton4MouseClicked


    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianAcc().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookButton;
    private javax.swing.JTextField author;
    private javax.swing.JTextField author1;
    private javax.swing.JButton editBookButton;
    private javax.swing.JTextField edition;
    private javax.swing.JTextField edition1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextField findBook;
    private javax.swing.JTextField findBook1;
    private javax.swing.JButton findBookB;
    private javax.swing.JButton findBookB1;
    private javax.swing.JTextField isbn;
    private javax.swing.JTextField isbn1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField keywords;
    private javax.swing.JTextField keywords1;
    private javax.swing.JTextField location;
    private javax.swing.JTextField location1;
    private javax.swing.JLabel loggedonuser;
    private javax.swing.JTextField pubdate;
    private javax.swing.JTextField pubdate1;
    private javax.swing.JTextField status;
    private javax.swing.JTextField status1;
    private javax.swing.JTable table;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTable table3;
    private javax.swing.JTextField title;
    private javax.swing.JTextField title1;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
